### ISSUE TITLE
 Create a Draft LUMENS Report in Quarto or RMarkdown for Land Use Change Analysis

### ISSUE THREAD

**Issue by dindiarto** [icraf-indonesia/LUMENSR#2]
**Description:**

The main goal of this issue is to create a report that presents the output of LUMENS land use change analysis (pre-ques). **A dummy version of the report is acceptable.** We currently have a report built on RTF, and we need to port it to either Quarto or RMarkdown. To decide which platform to use, we will compare the compatibility and error-proneness of Quarto and RMarkdown.

**Tasks:**

- [ ] Compare Quarto and RMarkdown for compatibility and error-proneness
- [ ] Choose the most suitable platform (Quarto or RMarkdown) based on the comparison
- [ ] Port the existing RTF report to the chosen platform
- [ ] Develop a draft LUMENS report for land use change analysis using the chosen platform
- [ ] Compile and generate the report through a command-line interface (terminal/cmd)

**Acceptance Criteria:**

- A document or list outlining the comparison between Quarto and RMarkdown in terms of compatibility and error-proneness
- A decision on which platform (Quarto or RMarkdown) to use for the LUMENS report
- A draft LUMENS report (can be a dummy) that presents the output of land use change analysis using the chosen platform
- Confirmation that the report can be generated through a command-line interface (terminal/cmd)

**Comment by dindiarto** [comment]
# Quarto vs RMarkdown Comparison

In order to help us make an informed decision between Quarto and RMarkdown, we should consider the following points:

- [ ] Which platform has a simpler installation process?
- [ ] Which platform results in smaller file sizes?
- [ ] Which platform is more efficient and quicker to execute?
